language: python  # Travis trabajará con Python, ya que Ren'Py está basado en este lenguaje
python:
  - "3.8"  # Usa la versión de Python que soporte Ren'Py
os:
  - windows  # Puedes cambiar a 'osx' o 'windows' si quieres probar en otros sistemas operativos

before_install:
  # Descargar Ren'Py
  - wget https://www.renpy.org/dl/8.0.3/renpy-8.0.3-sdk.tar.bz2
  - tar -xjf renpy-8.0.3-sdk.tar.bz2
  
  # Navegar al directorio donde está el SDK
  - cd renpy-8.0.3-sdk
  
script:
  # Ejecutar Ren'Py en modo compilación para verificar errores
  - ./renpy.sh ../el_libro_de_aventuras/ compile

